version: "3"
services:
  web:
    image: sikii/nexusphp_staff_bot:latest
    # build:
    #     context: .
    #     dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: bridge
    hostname: staff_bot
    container_name: staff_bot
    logging:
      driver: json-file
      options:
        max-size: 1m
    environment:
      - TZ=Asia/Shanghai
      # tg 机器人 token
      - BOT_TOKEN=xxxxxxxx
      # tg 群组 id
      - GROUP_ID=
      # 通用话题 id
      - GENERAL_THREAD_ID=
      # 管理组消息 话题 id
      - GENERAL_MSG_THREAD_ID=
      # 服务
      # 开启定时任务, 默认 15 分钟一次
      - STAFF_MSG_PERIOD=15
      - STAFF_MSG_ENABLE=true
      # - STAFF_MSG_ENABLE=false
      # 服务配置
      # mod+ 用户的 cookie, 要不然看不消息...
      - STAFF_MSG_COOKIE=xxxxxxxx
      ## 单独控制可选功能, 比如候选单独给种审拉个群
      # GROUP_ID 和 THREAD_ID 相关配置支持向上 fallback
      # XXXX_MSG_THREAD_ID=false 时, 支持发送消息到非话题群组, 除了 GENERAL_MSG_THREAD_ID
      # 管理组私信
      # GROUP_ID 和 THREAD_ID, 支持发送到不同群聊
      - STAFF_MSG_GROUP_ID=
      - STAFF_MSG_THREAD_ID=
      # 是否在消息里显示发送人, 只有设置为 false 才不显示
      - STAFF_MSG_SHOW_USER=
      # 是否禁用
      - STAFF_MSG_DISABLE_STAFF=false
      # 举报
      - REPORT_MSG_GROUP_ID=
      - REPORT_MSG_THREAD_ID=
      - REPORT_MSG_SHOW_USER=
      - STAFF_MSG_DISABLE_REPORT=false
      # 候选
      - OFFER_MSG_GROUP_ID=
      - OFFER_MSG_THREAD_ID=
      - OFFER_MSG_SHOW_USER=
      - STAFF_MSG_DISABLE_OFFER=false
      # 私信
      - MSG_MSG_GROUP_ID=
      - MSG_MSG_THREAD_ID=
      - MSG_MSG_SHOW_USER=
      - STAFF_MSG_DISABLE_MESSAGE=false
      # 站点schema
      - STAFF_MSG_SITE=PterClub
      # - STAFF_MSG_SITE=Xfree
      # - STAFF_MSG_SITE=Audiences
      # - STAFF_MSG_SITE=Ourbits
    volumes:
      # 部署多个的时候务必修改目录, 保证一个目录对应一个容器
      - ./bots/site/db:/app/db
      - ./bots/site/logs:/app/logs
